/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "dtpffryregemqlkogdhg"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0cGZmcnlyZWdlbXFsa29nZGhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQzMjQxODMsImV4cCI6MjA4OTkwMDE4M30.Zbg-ZQ8A8Jlk-F6QWiOixCN_2LxJrvrQwNThItE4Eu0"